
export function Email(props){
    var body = "";
    body = body + '<!DOCTYPE html> ';
    body = body + '<head> ';
    body = body + '<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> ';
    body = body + '<meta name="viewport" content="width=device-width, initial-scale=1.0" /> ';
    body = body + '<style> ';
    body = body +         '@import url(https://fonts.googleapis.com/css?family=Roboto:300); /*Calling our web font*/ ';
    body = body +         '#outlook a { padding:0; } ';
    body = body +         'body{ width:100% !important; -webkit-text-size-adjust:100%; -ms-text-size-adjust:100%; margin:0; padding:0; } ';
    body = body +         '.ReadMsgBody { width: 100%; } ';
    body = body +         '.ExternalClass {width:100%;} ';
    body = body +         '.backgroundTable {margin:0 auto; padding:0; width:100%;!important;} ';
    body = body +         'table td {border-collapse: collapse;} ';
    body = body +         '.ExternalClass * {line-height: 115%;} ';
    body = body +         '@media screen and (max-width: 630px){ ';
    body = body +             '*[class="mobile-column"] {display: block;} ';
    body = body +             '*[class="mob-column"] {float: none !important;width: 100% !important;} ';
    body = body +             '*[class="hide"] {display:none !important;} ';
    body = body +             '*[class="100p"] {width:100% !important; height:auto !important;} ';
    body = body +             '*[class="condensed"] {padding-bottom:40px !important; display: block;} ';
    body = body +             '*[class="center"] {text-align:center !important; width:100% !important; height:auto !important;} ';
    body = body +             '*[class="100pad"] {width:100% !important; padding:20px;} ';
    body = body +             '*[class="100padleftright"] {width:100% !important; padding:0 20px 0 20px;} ';
    body = body +             '*[class="100padtopbottom"] {width:100% !important; padding:20px 0px 20px 0px;} ';
    body = body +         '} ';
    body = body +     '</style> ';
    body = body + '<style type="text/css"> ';
    body = body + '</style> ';
    body = body + '</head><body> ';
    body = body + '<table class="header" width="600" height="50" border="0" align="center" cellpadding="0" cellspacing="0"> ';
    body = body + '</table><table width="600" border="0" align="center" cellpadding="0" cellspacing="0"> ';
    body = body +         '<tr bgcolor="#FFFFFF">  ';
    body = body +             '<td width="150" height="75"></td> ';
    body = body +             '<td><img src="' + props.logoImage + '" width="528" height="193" /> ';
    body = body +             '</td><td width="150" height="75"></td> ';
    body = body +         '</tr> ';
    body = body + '</table> ';
    body = body +     '<table width="600" border="0" align="center" cellpadding="0" cellspacing="0"> ';
    body = body +         '<tr><td height="5" bgcolor="#FFFFFF"></td></tr> ';
    body = body +         '<tr><td height="1" width="600" bgcolor="#dfdfdf"></td></tr> ';
    body = body +     '</table>  ';
    body = body + '<table width="600" border="0" align="center" cellpadding="0" cellspacing="0"> ';
    body = body +             '<tr><td height="20" bgcolor="#FFFFFF"></td></tr> ';
    body = body +         '</table> ';
    body = body +         '<center> ';
    body = body +     '<h1>Compra Realizada com Sucesso!</h1> ';
    body = body +     '<br/><br/> ';
    body = body +     '<h3>Endereço de Entrega</h3> ';
    body = body +     '<h4>' + props.Address + ' - ' + props.Bairro + '</h4> ';
    body = body +     '<h4>' + props.City + ' - ' + props.State + '</h4> ';
    body = body +     '<h4>CEP: ' + props.Cep + '</h4> ';
    body = body +     '<br/><br/> ';
    body = body +     '<h3>Prazo de Entrega</h3> ';
    body = body +     '<h4>15 dias úteis</h4> ';
    body = body + '</center> ';
    body = body + '<br /><br /><div align="center"> ';
    body = body + '©MMFSTORE 2020</span></td> ';
    body = body +     '<br></body></html>';
    return body;
}